/*
 * Types of the data files under data/, as the loader and the API read them.
 * The contract is data/README.md and docs/innovation-record.md; the record
 * shapes come from the JSON Schemas through schema-types.ts (generated by
 * scripts/build-data-types.mjs), and this file adds what the build, the
 * static-data builder and the hand-written files add, with the closed lists
 * of data/taxonomies.json as string literal unions.
 *
 * Checked against the real files: node scripts/build-data-types.mjs --check
 * (it also fails when a union and the taxonomies differ in either direction).
 * The screens' view model is separate, in src/lib/contracts/.
 */
import type { DerivedRecord, EvidenceItem, SourceRecord } from "./schema-types";

export type { DerivedRecord, EvidenceItem, SourceRecord };

// ----------------------------------------------------------- taxonomies (tax-v3)

export type TargetGroup =
  | "seniorzy"
  | "dzieci-mlodziez-rodziny"
  | "ograniczona-mobilnosc"
  | "niepelnosprawnosc-sensoryczna"
  | "zdrowie"
  | "rynek-pracy"
  | "cudzoziemcy"
  | "bezdomnosc"
  | "niepelnosprawnosc-intelektualna"
  | "spektrum-autyzmu"
  | "inne";

export type Domain =
  | "opieka-i-wsparcie-dzienne"
  | "samotnosc-i-izolacja"
  | "zdrowie-psychiczne"
  | "uzaleznienia"
  | "przemoc"
  | "ubostwo"
  | "mieszkalnictwo"
  | "mobilnosc-i-transport"
  | "dostepnosc"
  | "kompetencje-cyfrowe"
  | "edukacja"
  | "praca-i-aktywizacja"
  | "integracja-migrantow"
  | "opiekunowie-nieformalni"
  | "piecza-zastepcza"
  | "aktywnosc-obywatelska"
  | "samodzielnosc"
  | "zdrowie-fizyczne"
  | "kultura-sport-i-czas-wolny"
  | "prawa-i-sprawy-urzedowe"
  | "inne";

export type ImplementerType = "jst" | "ops-cus-pcpr" | "ngo" | "placowka" | "firma-pes" | "osoba";
export type CostBand = "low" | "medium" | "high" | "unknown";
export type TimeToImplement = "days" | "weeks" | "months" | "year-plus" | "unknown";
export type EvidenceLevel =
  | "described"
  | "tested"
  | "selected-for-dissemination"
  | "implemented-elsewhere"
  | "in-regional-model";
export type Setting = "rural" | "urban" | "any";
export type Scale = "individual" | "group" | "community";

interface Coded<C> {
  code: C;
  label_pl: string;
}

/** data/taxonomies.json. The mapping rules at the end serve the parser, not the app. */
export interface TaxonomiesFile {
  version: string;
  note: string;
  target_groups: (Coded<TargetGroup> & { rops_category_slug: string | null })[];
  domains: (Coded<Domain> & { hint_pl: string })[];
  implementer_types: (Coded<ImplementerType> & { national_base_value: string; paths_applicant_type: string })[];
  cost_bands: Coded<CostBand>[];
  time_to_implement: Coded<TimeToImplement>[];
  evidence_levels: Coded<EvidenceLevel>[];
  settings: Coded<Setting>[];
  scales: Coded<Scale>[];
  national_base_simple_tags: unknown;
  national_base_advanced_patterns: unknown;
  national_base_topic_patterns: unknown;
}

// ------------------------------------------------ built record (data/innovations)

export type SourceName = SourceRecord["source"];
export type Licence = SourceRecord["sources"][number]["licence"];
export type RecordSource = SourceRecord["sources"][number];

/** Set by derive-records.py build from .local/pipeline/link-check.json (check-links.py); absent before the first check. */
export type LinkStatus = "ok" | "dead" | "unknown";
export interface LinkCheck {
  link_status?: LinkStatus;
  link_checked_at?: string | null;
}

export type BuiltMaterial = SourceRecord["materials"][number] & LinkCheck;
export type BuiltLink = SourceRecord["links"][number] & LinkCheck;

/** The derived record without id and source_fingerprint, with the codes narrowed to the taxonomies. */
export interface BuiltDerived
  extends Omit<
    DerivedRecord,
    | "id"
    | "source_fingerprint"
    | "target_groups"
    | "domains"
    | "implementer_types"
    | "setting"
    | "scale"
    | "cost_band"
    | "time_to_implement"
    | "evidence_level"
  > {
  target_groups: TargetGroup[];
  domains: Domain[];
  implementer_types: ImplementerType[];
  setting: Setting;
  scale: Scale;
  cost_band: CostBand;
  time_to_implement: TimeToImplement;
  evidence_level: EvidenceLevel;
}

/** The parser's mechanical mapping, with the codes narrowed to the taxonomies. */
export interface BuiltMapped extends Omit<SourceRecord["mapped"], "target_groups" | "implementer_types" | "domain_hints"> {
  target_groups: TargetGroup[];
  implementer_types: ImplementerType[];
  domain_hints: Domain[];
}

/** data/innovations/<id>.json (innovation-record.md section 7): the source record without parsed_at, plus the build's fields. */
export interface BuiltInnovation extends Omit<SourceRecord, "parsed_at" | "materials" | "links" | "mapped"> {
  mapped: BuiltMapped;
  materials: BuiltMaterial[];
  links: BuiltLink[];
  derived: BuiltDerived;
  status: "active";
  /** Ids of the national-base entries merged into this ROPS record (FR-1.4). */
  merged_from?: string[];
  /** The source fields of the merged entry, keyed by its source name. */
  source_fields_secondary?: Partial<Record<SourceName, Record<string, string>>>;
}

/** One element of data/index-cards.json: the stage 1 index (FR-3.1). */
export interface IndexCard {
  id: string;
  title: string;
  card: string;
  target_groups: TargetGroup[];
  domains: Domain[];
  implementer_types: ImplementerType[];
  cost_band: CostBand;
  evidence_level: EvidenceLevel;
}

/** data/index-vectors.json (FR-3.7): unit-length vectors, cosine is a dot product. */
export interface IndexVectorsFile {
  model: string;
  dims: number;
  normalized: boolean;
  query_prefix: string;
  passage_prefix: string;
  document: string;
  /** Null only when data/data-version.json was missing at build time. */
  data_version: string | null;
  records_count: number;
  licence: string;
  vectors: Record<string, number[]>;
}

/** data/data-version.json (FR-1.7). */
export interface DataVersion {
  version: string;
  records: number;
  merged: number;
  skipped_without_valid_derived: number;
  prompt_version: string;
  parser_version: string;
  built_at: string;
}

/** data/incubators.json (parse-catalogues.py, the incubator profiles of the national base). */
export interface Incubator {
  uuid: string;
  name: string;
  years: string | null;
  programme: "POWER 4.1" | "FERS" | null;
  url: string;
  website: string | null;
  innovation_slugs: string[];
  rops: boolean;
}
export interface IncubatorsFile {
  source: string;
  retrieved_at: string;
  incubators: Incubator[];
}

/** One entry of data/duplicates-decisions.json (hand-written, FR-1.4). */
interface DecisionBase {
  ids: [string, string];
  title: string;
  reason: string;
  decided_by: string;
  decided_on: string;
}
export type DuplicateDecision =
  | (DecisionBase & { decision: "keep-both" })
  | (DecisionBase & { decision: "merge"; primary: string; secondary: string });
export interface DuplicateDecisionsFile {
  note: string;
  decisions: DuplicateDecision[];
}

// --------------------------------------------------------- places, map, indicators

export type GminaKind = "gmina miejska" | "gmina wiejska" | "gmina miejsko-wiejska";

/** A place of data/places/pl-register.json (8.9); terc is the code without PL- and hyphens. */
export interface Voivodeship {
  code: string;
  terc: string;
  level: "wojewodztwo";
  name: string;
  parent: null;
}
export interface Powiat {
  code: string;
  terc: string;
  level: "powiat";
  name: string;
  kind: string;
  parent: string;
}
export interface GminaPlace {
  code: string;
  terc: string;
  level: "gmina";
  name: string;
  kind: GminaKind;
  parent: string;
  powiat: string;
  wojewodztwo: string;
  /** The picker label, e.g. "Kraków (miasto na prawach powiatu)". */
  label: string;
  /** [lon, lat], WGS 84; absent when the boundary file has no such gmina. */
  centroid?: [number, number];
}
export type Place = Voivodeship | Powiat | GminaPlace;
export interface PlacesRegister {
  source: string;
  stan_na: string;
  retrieved_at: string;
  centroids: string;
  codes: string;
  counts: { wojewodztwa: number; powiaty: number; gminy: number };
  places: Place[];
}

/** A town, village or Kraków delegatura of data/places/malopolska-localities.json; terc is its gmina. */
export interface LocalityPlace {
  /** Seven-digit SIMC identifier. */
  simc: string;
  name: string;
  kind: "wieś" | "miasto" | "delegatura";
  terc: string;
}
export interface LocalitiesFile {
  source: string;
  stan_na: string;
  retrieved_at: string;
  scope: string;
  counts: Partial<Record<LocalityPlace["kind"], number>>;
  localities: LocalityPlace[];
}

/** data/map/malopolska-gminy.geojson (8.8). */
export interface GminaBoundaryProperties {
  /** Seven-digit TERC. */
  JPT_KOD_JE: string;
  JPT_NAZWA_: string;
  kind: GminaKind;
  powiat: string;
}
export interface GminaBoundaries {
  type: "FeatureCollection";
  source: string;
  features: {
    type: "Feature";
    properties: GminaBoundaryProperties;
    geometry: { type: "Polygon"; coordinates: number[][][] } | { type: "MultiPolygon"; coordinates: number[][][][] };
  }[];
}

/** data/indicators.json (8.8, FR-7.2). */
export type IndicatorKey = "social-assistance" | "ageing" | "unemployment" | "civic-density";
export interface IndicatorValue {
  value: number;
  year: number;
  /** BDL attribute symbol and its Polish text when the value is not plain. */
  flag?: string;
  flag_pl?: string;
}
export interface IndicatorGmina {
  terc: string;
  name: string;
  kind: GminaKind;
  powiat: string;
  /** Empty for a gmina without data (Szczawa, 1207132). */
  values: Partial<Record<IndicatorKey, IndicatorValue>>;
}
export interface IndicatorMeta {
  key: IndicatorKey;
  variable_id: number;
  name_pl: string | null;
  unit_pl: string | null;
  subject_id: string | null;
  year: number | null;
  years_used: number[];
  gminas_with_value: number;
  median: number | null;
  min: number | null;
  max: number | null;
}
export interface IndicatorsFile {
  source: {
    name: string;
    url: string;
    licence: string;
    retrieved_at: string;
    unit_parent_id: string;
    unit_level: number;
  };
  note: string;
  indicators: IndicatorMeta[];
  /** Which indicators express need per target group; "default" for every other group. */
  need_by_target_group: Partial<Record<TargetGroup, IndicatorKey[]>> & { default: IndicatorKey[] };
  /** Keyed by the seven-digit TERC. */
  gminas: Record<string, IndicatorGmina>;
  /** TERC to the indicators without a value. */
  missing: Record<string, IndicatorKey[]>;
}

// ------------------------------------------------------ people: implementations, advisors

export type ImplementationStatus = "running" | "completed" | "planned";
export type ImplementationSource =
  | "catalogue-origin"
  | "usluga-wrazliwa"
  | "regional-model"
  | "partner"
  | "user-reported"
  | "demo";

interface ImplementationBase {
  id: string;
  innovation_id: string;
  status: ImplementationStatus;
  source: ImplementationSource;
  source_url: string;
  note_pl: string;
}

/** A row of data/implementations.yaml (hand-written seeds, 8.6); the organisation is nested, not an id. */
export interface SeededImplementation extends ImplementationBase {
  /** Null for a voivodeship-wide regional model or a place not yet known (see note_pl). */
  place_terc: string | null;
  place_name?: string;
  organisation?: { name_pl: string; type: ImplementerType; source_url?: string };
  year?: number;
  project_title_pl?: string;
}

/** A row of data/implementations-derived.json: the place of origin of a built record (build-static-data.py, step origins). */
export interface DerivedImplementation extends ImplementationBase {
  source: "catalogue-origin";
  status: "completed";
  place_terc: string;
  place_name: string;
  match: "gmina" | "gmina, town preferred" | "gmina, city preferred among namesakes" | "locality";
  year: number | null;
}

export type Implementation = SeededImplementation | DerivedImplementation;

export interface ImplementationsFile {
  version: string;
  sources: Record<string, { url: string; results_on?: string }>;
  implementations: SeededImplementation[];
}
export interface ImplementationsDerivedFile {
  note: string;
  data_version: string | null;
  matching: string;
  implementations: DerivedImplementation[];
  unmatched: { innovation_id: string; place: string; reason: string }[];
}

/** A row of data/implementations-merged.json: a seed or an origin, with the row of organisations.json and the file it comes from. */
export type MergedImplementation =
  | (SeededImplementation & { organisation_id: string | null; origin_file: "data/implementations.yaml" })
  | (DerivedImplementation & { organisation_id: string | null; origin_file: "data/implementations-derived.json" });

/** data/implementations-merged.json (build-static-data.py, step organisations; 8.6, FR-6.3): the map and the route read this file. */
export interface ImplementationsMergedFile {
  note: string;
  data_version: string | null;
  /** The version of data/implementations.yaml. */
  seeds_version: string;
  sources: ImplementationsFile["sources"];
  counts: {
    implementations: number;
    by_origin_file: Partial<Record<MergedImplementation["origin_file"], number>>;
    innovations_with_implementation: number;
    innovations_with_implementation_in_malopolska: number;
    with_organisation: number;
    deduplicated: number;
    organisations_by_type: OrganisationTypeCounts;
  };
  implementations: MergedImplementation[];
  /** Origins dropped because a seed covers the same innovation and gmina. */
  deduplicated: { id: string; covered_by: string }[];
}

// ------------------------------------------------------------------- organisations

export type OrganisationSource = "catalogue" | "seed";
export type NaturalPersonReason = "osoba-fizyczna" | "grupa-nieformalna" | "person-name" | "authors-persons-only";
/** Rows per type code; the rows without a type are counted under "untyped". */
export type OrganisationTypeCounts = Partial<Record<ImplementerType | "untyped", number>>;

/** A row of data/organisations.json (8.6, FR-6.1). No e-mail, phone or postal address; the app links the source entry. */
export interface Organisation {
  /** org-<ascii slug>. */
  id: string;
  name: string;
  /** Null when the name matches no rule of type_rules; type_note says why. */
  type: ImplementerType | null;
  type_note: string | null;
  website: string | null;
  place_terc: string | null;
  place_name: string | null;
  /** How the place was resolved: as in the origins step, "seed" for a place taken from data/implementations.yaml. */
  place_match: DerivedImplementation["match"] | "seed" | null;
  /** Records the organisation authored. */
  innovation_ids: string[];
  /** Rows of data/implementations-merged.json. */
  implementation_ids: string[];
  source: OrganisationSource;
  source_urls: string[];
  contact_opt_out: false;
}

/** data/organisations.json (build-static-data.py, step organisations). */
export interface OrganisationsFile {
  note: string;
  data_version: string | null;
  privacy: string;
  type_rules: string;
  grouping: string;
  reasons: Record<NaturalPersonReason, string>;
  counts: {
    organisations: number;
    by_type: OrganisationTypeCounts;
    by_source: Partial<Record<OrganisationSource, number>>;
    natural_person_innovations: number;
    natural_person_by_reason: Partial<Record<NaturalPersonReason, number>>;
    without_organisation: number;
  };
  organisations: Organisation[];
  /** Records of natural persons: the innovation id only, never a name (R6, FR-1.9). */
  natural_person_innovations: { innovation_id: string; reason: NaturalPersonReason }[];
  /** Ids of the records that name neither an organisation nor a person. */
  without_organisation: string[];
  /** For the reviewers, not the app. */
  review: {
    merged_variants: string[][];
    similar_not_merged: [string, string][];
    type_notes: (
      | { name: string; type: ImplementerType | null; variant_types: (ImplementerType | "untyped")[] }
      | { name: string; type: ImplementerType | null; seed_type: ImplementerType }
    )[];
    persons_removed: string[];
  };
}

// ---------------------------------------------------------- knowledge, helplines

/** A list of target-group codes, or exactly [any]. */
export type TargetGroupsOrAny = TargetGroup[] | ["any"];

export type KnowledgeType = "guide" | "model" | "publication" | "catalogue" | "data" | "contact" | "project";

/** An item of data/knowledge.yaml (hand-written, FR-4.3). */
export interface KnowledgeItem {
  id: string;
  title_pl: string;
  description_pl: string;
  url: string;
  type: KnowledgeType;
  target_groups: TargetGroupsOrAny;
  /** True: on every route. */
  always_show: boolean;
  /** The page that lists the item. */
  source_url: string;
  verified_on: string;
}

/** data/knowledge.yaml: the fixed links of the route's knowledge block. */
export interface KnowledgeFile {
  version: string;
  verified_on: string;
  /** Per target-group code, the ids of the items the composer adds. */
  model_by_target_group: Record<TargetGroup, string[]>;
  items: KnowledgeItem[];
}

/** A number of data/helplines.yaml (S10, S12, 12.6); 112 first. */
export interface Helpline {
  id: string;
  order: number;
  /** alarm: "Numery alarmowe"; support: "Pomoc i rozmowa" (FR-12.5). */
  group: "alarm" | "support";
  name_pl: string;
  /** As dialled, with spaces, e.g. "116 123". */
  number: string;
  hours_pl: string;
  who_for_pl: string;
  /** Only free helplines are listed. */
  free: true;
  url: string;
  source_url: string;
  verified_on: string;
}

/** data/helplines.yaml (hand-written, OP-33). */
export interface HelplinesFile {
  version: string;
  verified_on: string;
  note_pl: string;
  /** Null until the lawyer confirms the list (OP-33). */
  reviewer: string | null;
  helplines: Helpline[];
}

// ------------------------------------------------------------------------- paths

/** The closed lists of scripts/check-paths.py. */
export type PathApplicantType = "jst" | "ngo" | "pes" | "mieszkancy";
export type PathDecides = "jst" | "ngo" | "mieszkancy" | "panstwo" | "operator-ue";
export type PathPurpose =
  | "zadanie-publiczne"
  | "inicjatywa-mieszkancow"
  | "program-uslug-spolecznych"
  | "wdrozenie-innowacji"
  | "testowanie-innowacji"
  | "doradztwo"
  | "rozwoj-organizacji"
  | "wolontariat"
  | "usluga-opiekuncza"
  | "tworzenie-miejsc"
  | "dostepnosc"
  | "wspolpraca-miedzynarodowa";
/** lokalna: every gmina; malopolska and krakow: regional; krajowa and ue: national and EU programmes. */
export type PathScope = "lokalna" | "malopolska" | "krakow" | "krajowa" | "ue";
export type PathTimingKind = "rolling" | "annual" | "fixed" | "closed" | "per-call";
export type PathRole = "pracownik-instytucji" | "organizacja-spoleczna" | "mieszkaniec" | "urzad-gminy";

/** A call of a path; the dates are ISO (YYYY-MM-DD). */
export interface PathCall {
  label_pl: string;
  /** A subset of the path's applicant_types. */
  applicant_types: PathApplicantType[];
  opens_on: string | null;
  closes_on: string;
}

/** data/paths/<id>.yaml (8.7, FR-8.1): one legal or funding path, validated by scripts/check-paths.py. */
export interface Path {
  /** Equal to the file name. */
  id: string;
  name_pl: string;
  legal_basis_pl: string;
  applicant_types: PathApplicantType[];
  decides: PathDecides;
  purposes: PathPurpose[];
  target_groups: TargetGroupsOrAny;
  scope: PathScope;
  amount_min_pln: number | null;
  amount_max_pln: number | null;
  /** EUR amounts are only here. */
  amount_note_pl: string;
  timing: {
    kind: PathTimingKind;
    note_pl: string;
    /** For annual, the latest known call; the app rolls a passed closes_on forward by a year. */
    calls: PathCall[];
  };
  decision_maker_pl: string;
  /** Three imperative sentences, at most 12 words each. */
  steps_pl: string[];
  fit: {
    cost_bands: CostBand[];
    roles: PathRole[];
    boost_when_implementer_types: ImplementerType[];
  };
  source_url: string;
  verified_on: string;
  /** No legal review in the hackathon. */
  reviewer: null;
  /** Opens with the prototype note of FR-1.8, then "Sprawdź u źródła.". */
  notes_pl: string;
}

/** One row of data/advisors.yaml per target group (FR-6.2); name stays null until ROPS publishes one (OP-10). */
export interface Advisor {
  category: TargetGroup;
  name: string | null;
  role: string;
  email: string;
  phone: string;
  source_url: string;
}
export interface AdvisorsFile {
  version: string;
  source_url: string;
  verified_on: string;
  department: { name_pl: string; address_pl: string; hours_pl: string; email: string; phones: string[] };
  programme_contacts: Record<string, { name_pl: string; email: string; source_url: string }>;
  advisors: Advisor[];
}
